In [ ]:
import numpy as np

a = np.array([22, 25, 26, 27, 30])
print(a)
print(a.shape)

[22 25 26 27 30]
(5,)


In [ ]:
b = np.array([[1,2,3, 7], [4,5,6, 8]])
print(b)
print(b.shape)

[[1 2 3 7]
 [4 5 6 8]]
(2, 4)


In [ ]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11,12]]])
print(c)
print(c.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
h = np.array([1,2,3], dtype=float)


dtype('float64')

In [ ]:
h.dtype

dtype('float64')

In [ ]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# np.arange(16)
# np.arange(16).reshape(4,4)
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
# np.ones((3,4))
# np.zeros((3,4))
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [ ]:
np.random.random((3,4))

array([[0.81982183, 0.01359553, 0.02981931, 0.32759006],
       [0.43330511, 0.15091987, 0.7994008 , 0.03019885],
       [0.64542721, 0.6232868 , 0.23836917, 0.97692193]])

In [ ]:
# linespace: provide 3 things, 1st one lower range, 2nd one upper range, 3rd one how much element linearly generated
np.linspace(2, 7, 4, dtype=int)
np.linspace(-10,10 , 10, dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [ ]:
a3.ndim

3

In [ ]:
# a2.shape
a2.size

12

In [ ]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [ ]:
a1 = np.arange(12).reshape(3, 4)
a2 = np.arange(12, 24).reshape(3, 4)
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [ ]:
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
#Vector operations

# a1 + a2
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3[1,0,1]

np.int64(1)

In [ ]:
a2[2,]

array([ 8,  9, 10, 11])

In [ ]:
a2[:,1]

array([1, 5, 9])

In [ ]:
a2[0:2,  1:3]

array([[1, 2],
       [5, 6]])

In [ ]:
a1[-3]

np.int64(7)

In [ ]:
a2[2,3]

np.int64(11)

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[2,1:3,1:3]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[2, 0:, 0]

array([18, 21, 24])