In [ ]:
import numpy as np

a = np.array([22, 25, 26, 27, 30])
print(a)
print(a.shape)

[22 25 26 27 30]
(5,)


In [ ]:
b = np.array([[1,2,3, 7], [4,5,6, 8]])
print(b)
print(b.shape)

[[1 2 3 7]
 [4 5 6 8]]
(2, 4)


In [ ]:
c = np.array([[[1,2], [3,4]], [[5,6], [7,8]], [[9,10], [11,12]]])
print(c)
print(c.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [ ]:
h = np.array([1,2,3], dtype=float)


dtype('float64')

In [ ]:
h.dtype

dtype('float64')

In [ ]:
np.arange(20,50)

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])